# coding=utf-8
__author__ = 'newdefence@163.com'
__date__ = "2017/7/26 上午1:14:00"

WEIBO_OAUTH_CLIENT_ID = "TODO:"
WEIBO_OAUTH_CLIENT_SECRET = "TODO:"

QQ_OAUTH_CLIENT_ID = "TODO:"
QQ_OAUTH_CLIENT_SECRET = "TODO:"

WEIXIN_OAUTH_CLIENT_ID = "TODO:"
WEIXIN_OAUTH_CLIENT_SECRET = "TODO:"